name: Deploy to Oracle

on:
  push:
    branches:
      - main  # Ensure this matches your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy backend files via SSH
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "backend/*"
        target: "/home/ubuntu/AgentQuiz/backend/"

    - name: Copy frontend files via SSH
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "frontend/*"
        target: "/home/ubuntu/AgentQuiz/frontend/"

    - name: Restart service
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo systemctl restart agentquiz
